server:
  port: 7070
spring:
  application:
    name: bank-statement
  ##### Datasource Configuration #####
  datasource:
    driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
    url: jdbc:ucanaccess://E:/DIR/accountsdb.accdb;openExclusive=false;ignoreCase=true
#    url: jdbc:ucanaccess://E:/accountsdb.accdb;openExclusive=false;ignoreCase=true


###### session configuration ######
session:
  expiration: 864000000 #10 days

###### token configuration ######
token:
  secret: jf9i4jgu83nfl0jfu57ejf7
  prefix: Bearer
header:
  authorization: Authorization